Repository CSC207-2022F-UofT/course-project-shazamify, pull requests merged in 2022-12, with the labels that each got.

#81 General violation fixes + updated documentation
  src/main/java/abr/queue_abr/history/HistoryInputBoundary.java
  src/main/java/abr/queue_abr/queue/QueueInputBoundary.java
  src/main/java/abr/queue_abr/queue/QueueOutputBoundary.java
  src/main/java/abr/queue_abr/queue/QueueUseCase.java
  src/main/java/framework/queue_screen/QueueManagerUI.java
  src/main/java/interface_adaptors/queue_ia/QueueController.java
  src/main/java/interface_adaptors/queue_ia/QueuePresenter.java
  src/test/java/queue_abr_test/UpdateQueueTest.java
Labels: documentation, hotfix

#87 Created main.yml workflow
  .github/workflows/main.yml
Labels: enhancement

#125 Updated all javadocs fixed some implementation
  src/main/java/abr/queue_abr/history/HistoryInputBoundary.java
  src/main/java/abr/queue_abr/history/HistoryUseCase.java
  src/main/java/abr/queue_abr/queue/QueueFDTO.java
  src/main/java/abr/queue_abr/queue/QueueFHelper.java
  src/main/java/abr/queue_abr/queue/QueueFReqM.java
  src/main/java/abr/queue_abr/queue/QueueFUC.java
  src/main/java/abr/queue_abr/queue/QueueGetDTO.java
  src/main/java/abr/queue_abr/queue/QueueGetHelper.java
  src/main/java/abr/queue_abr/queue/QueueGetInputBoundary.java
  src/main/java/abr/queue_abr/queue/QueueGetOutputBoundary.java
  src/main/java/abr/queue_abr/queue/QueueGetRequestModel.java
  src/main/java/abr/queue_abr/queue/QueueGetResponseModel.java
  src/main/java/abr/queue_abr/queue/QueueGetUseCase.java
  src/main/java/abr/queue_abr/queue/QueueUHelper.java
  src/main/java/abr/queue_abr/queue/QueueUUseCase.java
  src/main/java/framework/queue_screen/QueueManagerUI.java
  src/main/java/interface_adaptors/queue_ia/QueueFirstController.java
  src/main/java/interface_adaptors/queue_ia/QueueFirstPresenter.java
  src/main/java/interface_adaptors/queue_ia/QueueGetController.java
  src/main/java/interface_adaptors/queue_ia/QueueGetPresenter.java
  src/main/java/interface_adaptors/queue_ia/QueueUController.java
  src/test/java/queue_abr_test/QueueUpdate.java
  src/test/java/queue_abr_test/UpdateQueueTest.java
Labels: documentation, hotfix, tests

#130 One small step for queue, One large leap for functionality
  src/main/java/abr/song_abr/SongDTO.java
  src/main/java/interface_adaptors/queue_ia/QueueFirstPresenter.java
  src/main/java/interface_adaptors/queue_ia/QueueGetPresenter.java
  src/main/java/interface_adaptors/queue_ia/QueueViewModel.java
  src/test/java/queue_abr_test/GetQueueTest.java
  src/test/java/queue_abr_test/UpdateQueueTest.java
Labels: bug, enhancement, tests

#188 Implemented seekEndSong button.
  src/main/java/interface_adaptors/display_ia/SongPlayerAudio.java
Labels: hotfix
